//package com.cgcl.entities;
//
//import java.util.Date;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.Id;
//import javax.persistence.Table;
//
//import lombok.Data;
//
//@Entity
//@Table(name = "psx_report_input_output")
//@Data
//public class CGCL_REPORT_INPUT_OUTPUT {
//	
//	@Id
//	@Column(name="REQUEST_ID") 
//	public long requestid;
//	@Column(name = "AADHAR_NO")  
//	private String aadharno;
//	@Column(name = "ACCOUNT_STATUS")  
//	private String accountstatus;
//	@Column(name = "APPLICANT_FULL_NAME")  
//	private String applicantfullname;
//	@Column(name = "BATCH_ID")  
//	private String batchid;
//	@Column(name = "CIBIL_SCORE")  
//	private String cibilscore;
//	@Column(name = "CIN")  
//	private String cin;
//	@Column(name = "CKYC_NO")  
//	private String ckycno;
//	@Column(name = "CUSTOMER_CATEGORY_TYPE")  
//	private String customercategorytype;
//	@Column(name = "CUSTOMER_NO")  
//	private String customerno;
//	@Column(name = "CUSTOMER_TYPE_CODE")  
//	private String customertypecode;
//	@Column(name = "CUST_ID")  
//	private String custid;
//	@Column(name = "DEAL_ID_APP_ID")  
//	private String dealidappid;
//	@Column(name = "DIN")  
//	private String din;
//	@Column(name = "DOB")  
//	private Date dob;
//	@Column(name = "DRIVING_LIC_NO")  
//	private String drivinglicno;
//	@Column(name = "DUIFLAG")  
//	private String duiflag;
//	@Column(name = "EVENTTYPE")  
//	private String eventtype;
//	@Column(name = "FATHER_NAME")  
//	private String fathername;
//	@Column(name = "FIRST_NAME")  
//	private String firstname;
//	@Column(name = "GENDER")  
//	private String gender;
//	@Column(name = "GSTIN")  
//	private String gstin;
//	@Column(name = "HIGHEST_EDUCATION")  
//	private String highesteducation;
//	@Column(name = "LAST_NAME")  
//	private String lastname;
//	@Column(name = "LEAD_ID")  
//	private String leadid;
//	@Column(name = "MARITAL_STATUS")  
//	private String maritalstatus;
//	@Column(name = "MIDDLE_NAME")  
//	private String middlename;
//	@Column(name = "MOTHER_MAIDEN_NAME")  
//	private String mothermaidenname;
//	@Column(name = "MOTHER_NAME")  
//	private String mothername;
//	@Column(name = "NAME")  
//	private String name;
//	@Column(name = "OLD_PSX_BATCH_ID")  
//	private String oldpsxbatchid;
//	@Column(name = "PAN_NO")  
//	private String panno;
//	@Column(name = "PASSPORT_NO")  
//	private String passportno;
//	@Column(name = "PRIMARY_OCCUPATION")  
//	private String primaryoccupation;
//	@Column(name = "PSX_BATCH_ID")  
//	private String psxbatchid;
//	@Column(name = "RESIDENT_STATUS")  
//	private String residentstatus;
//	@Column(name = "SOURCE_SYSTEM")  
//	private String sourcesystem;
//	@Column(name = "SPOUSE_NAME")  
//	private String spousename;
//	@Column(name = "TAN")  
//	private String tan;
//	@Column(name = "TAX_ID")  
//	private String taxid;
//	@Column(name = "UCIC")  
//	private String ucic;
//	@Column(name = "UCIC_TYPE")  
//	private String ucictype;
//	@Column(name = "UID")  
//	private int uid;
//	@Column(name = "UID_TYPE")  
//	private String uidtype;
//	@Column(name = "VOTER_ID_NO")  
//	private String voteridno;
//	@Column(name = "ADDRESS_0")  
//	private String address0;
//	@Column(name = "ADDRESS_ID_0")  
//	private String addressid0;
//	@Column(name = "ADDRESS_TYPE_0")  
//	private String addresstype0;
//	@Column(name = "CITY_0")  
//	private String city0;
//	@Column(name = "CUSTOMER_CONTACT_0")  
//	private String customercontact0;
//	@Column(name = "CUSTOMER_CONTACT_TYPE_0")  
//	private String customercontacttype0;
//	@Column(name = "CUSTOMER_LANDLINE_0")  
//	private String customerlandline0;
//	@Column(name = "CUSTOMER_LANDLINE_TYPE_0")  
//	private String customerlandlinetype0;
//	@Column(name = "CUSTOMER_NO_0")  
//	private String customerno0;
//	@Column(name = "EMAIL_0")  
//	private String email0;
//	@Column(name = "EMAIL_TYPE_0")  
//	private String emailtype0;
//	@Column(name = "PINCODE_0")  
//	private String pincode0;
//	@Column(name = "STATE_0")  
//	private String state0;
//	@Column(name = "ADDRESS_1")  
//	private String address1;
//	@Column(name = "ADDRESS_ID_1")  
//	private String addressid1;
//	@Column(name = "ADDRESS_TYPE_1")  
//	private String addresstype1;
//	@Column(name = "CITY_1")  
//	private String city1;
//	@Column(name = "CUSTOMER_CONTACT_1")  
//	private String customercontact1;
//	@Column(name = "CUSTOMER_CONTACT_TYPE_1")  
//	private String customercontacttype1;
//	@Column(name = "CUSTOMER_LANDLINE_1")  
//	private String customerlandline1;
//	@Column(name = "CUSTOMER_LANDLINE_TYPE_1")  
//	private String customerlandlinetype1;
//	@Column(name = "CUSTOMER_NO_1")  
//	private String customerno1;
//	@Column(name = "EMAIL_1")  
//	private String email1;
//	@Column(name = "EMAIL_TYPE_1")  
//	private String emailtype1;
//	@Column(name = "PINCODE_1")  
//	private String pincode1;
//	@Column(name = "STATE_1")  
//	private String state1;
//	@Column(name = "ADDRESS_2")  
//	private String address2;
//	@Column(name = "ADDRESS_ID_2")  
//	private String addressid2;
//	@Column(name = "ADDRESS_TYPE_2")  
//	private String addresstype2;
//	@Column(name = "CITY_2")  
//	private String city2;
//	@Column(name = "CUSTOMER_CONTACT_2")  
//	private String customercontact2;
//	@Column(name = "CUSTOMER_CONTACT_TYPE_2")  
//	private String customercontacttype2;
//	@Column(name = "CUSTOMER_LANDLINE_2")  
//	private String customerlandline2;
//	@Column(name = "CUSTOMER_LANDLINE_TYPE_2")  
//	private String customerlandlinetype2;
//	@Column(name = "CUSTOMER_NO_2")  
//	private String customerno2;
//	@Column(name = "EMAIL_2")  
//	private String email2;
//	@Column(name = "EMAIL_TYPE_2")  
//	private String emailtype2;
//	@Column(name = "PINCODE_2")  
//	private String pincode2;
//	@Column(name = "STATE_2")  
//	private String state2;
//	@Column(name = "ADDRESS_3")  
//	private String address3;
//	@Column(name = "ADDRESS_ID_3")  
//	private String addressid3;
//	@Column(name = "ADDRESS_TYPE_3")  
//	private String addresstype3;
//	@Column(name = "CITY_3")  
//	private String city3;
//	@Column(name = "CUSTOMER_CONTACT_3")  
//	private String customercontact3;
//	@Column(name = "CUSTOMER_CONTACT_TYPE_3")  
//	private String customercontacttype3;
//	@Column(name = "CUSTOMER_LANDLINE_3")  
//	private String customerlandline3;
//	@Column(name = "CUSTOMER_LANDLINE_TYPE_3")  
//	private String customerlandlinetype3;
//	@Column(name = "CUSTOMER_NO_3")  
//	private String customerno3;
//	@Column(name = "EMAIL_3")  
//	private String email3;
//	@Column(name = "EMAIL_TYPE_3")  
//	private String emailtype3;
//	@Column(name = "PINCODE_3")  
//	private String pincode3;
//	@Column(name = "STATE_3")  
//	private String state3;
//	@Column(name = "ADDRESS_4")  
//	private String address4;
//	@Column(name = "ADDRESS_ID_4")  
//	private String addressid4;
//	@Column(name = "ADDRESS_TYPE_4")  
//	private String addresstype4;
//	@Column(name = "CITY_4")  
//	private String city4;
//	@Column(name = "CUSTOMER_CONTACT_4")  
//	private String customercontact4;
//	@Column(name = "CUSTOMER_CONTACT_TYPE_4")  
//	private String customercontacttype4;
//	@Column(name = "CUSTOMER_LANDLINE_4")  
//	private String customerlandline4;
//	@Column(name = "CUSTOMER_LANDLINE_TYPE_4")  
//	private String customerlandlinetype4;
//	@Column(name = "CUSTOMER_NO_4")  
//	private String customerno4;
//	@Column(name = "EMAIL_4")  
//	private String email4;
//	@Column(name = "EMAIL_TYPE_4")  
//	private String emailtype4;
//	@Column(name = "PINCODE_4")  
//	private String pincode4;
//	@Column(name = "STATE_4")  
//	private String state4;
//	@Column(name = "MATCH_TYPE")  
//	private String matchtype;
//	@Column(name = "SCALE_TYPE")  
//	private String scaletype;
//	@Column(name = "INPUT_PSX_BATCH_ID")  
//	private String inputpsxbatchid;
//	@Column(name = "RECORD_TYPE")  
//	private String recordtype;
//	@Column(name = "psx_target_fcb")  
//	private String psxtargetfcb;
//	@Column(name = "INSERT_TIME")  
//	private Date inserttime;
//	@Column(name = "RANK1")  
//	private String rank1;
//	@Column(name = "CSCORE")  
//	private String cscore;
//	@Column(name = "MRNAME")  
//	private String mrname;
//	@Column(name = "LCHGTIME")  
//	private Date lchgtime;
//	@Column(name = "CUST_UNQ_ID")  
//	private String custunqid;
//}